name: Klink Payment DEV
on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: klink-payment/be           # set this to your Amazon ECR repository name
  S3_BUCKET: k-link-aws-codedeploy-deployments
  S3_FOLDER: klink-payment-api-go-dev

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR (Core)
        id: build-image-core
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          APP_VERSION: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR

          docker build -f cicd/local/Dockerfile \
          --build-arg ARG_APP_VERSION=dev \
          --build-arg ARG_SERVICE_SLUG=payment-service \
          --build-arg ARG_PORT=10000 \
          --tag $ECR_REGISTRY/$ECR_REPOSITORY:dev .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:dev" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest  

    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name "klink-payment-api-go" \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name "klink-payment-api-go-dev" \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=$S3_BUCKET,key=klink-payment-api-go-dev/application.zip,bundleType=zip \
